import * as flags from 'Assets/images/Flags'

const PHONES = [
  {
    country: 'Afghanistan',
    phone: '+93',
    code: 'AF / AFG',
    flag: null,
  },
  {
    country: 'Albania',
    phone: '+355',
    code: 'AL / ALB',
    flag: null,
  },
  {
    country: 'Algeria',
    phone: '+213',
    code: 'DZ / DZA',
    flag: null,
  },
  {
    country: 'American Samoa',
    phone: '+1-684',
    code: 'AS / ASM',
    flag: null,
  },
  {
    country: 'Andorra',
    phone: '+376',
    code: 'AD / AND',
    flag: null,
  },
  {
    country: 'Angola',
    phone: '+244',
    code: 'AO / AGO',
    flag: null,
  },
  {
    country: 'Anguilla',
    phone: '+1-264',
    code: 'AI / AIA',
    flag: null,
  },
  {
    country: 'Antarctica',
    phone: '+672',
    code: 'AQ / ATA',
    flag: null,
  },
  {
    country: 'Antigua and Barbuda',
    phone: '+1-268',
    code: 'AG / ATG',
    flag: null,
  },
  {
    country: 'Argentina',
    phone: '+54',
    code: 'AR / ARG',
    flag: null,
  },
  {
    country: 'Armenia',
    phone: '+374',
    code: 'AM / ARM',
    flag: null,
  },
  {
    country: 'Aruba',
    phone: '+297',
    code: 'AW / ABW',
    flag: null,
  },
  {
    country: 'Australia',
    phone: '+61',
    code: 'AU / AUS',
    flag: null,
  },
  {
    country: 'Austria',
    phone: '+43',
    code: 'AT / AUT',
    flag: null,
  },
  {
    country: 'Azerbaijan',
    phone: '+994',
    code: 'AZ / AZE',
    flag: null,
  },
  {
    country: 'Bahamas',
    phone: '+1-242',
    code: 'BS / BHS',
    flag: null,
  },
  {
    country: 'Bahrain',
    phone: '+973',
    code: 'BH / BHR',
    flag: null,
  },
  {
    country: 'Bangladesh',
    phone: '+880',
    code: 'BD / BGD',
    flag: null,
  },
  {
    country: 'Barbados',
    phone: '+1-246',
    code: 'BB / BRB',
    flag: null,
  },
  {
    country: 'Belarus',
    phone: '+375',
    code: 'BY / BLR',
    flag: null,
  },
  {
    country: 'Belgium',
    phone: '+32',
    code: 'BE / BEL',
    flag: null,
  },
  {
    country: 'Belize',
    phone: '+501',
    code: 'BZ / BLZ',
    flag: null,
  },
  {
    country: 'Benin',
    phone: '+229',
    code: 'BJ / BEN',
    flag: null,
  },
  {
    country: 'Bermuda',
    phone: '+1-441',
    code: 'BM / BMU',
    flag: null,
  },
  {
    country: 'Bhutan',
    phone: '+975',
    code: 'BT / BTN',
    flag: null,
  },
  {
    country: 'Bolivia',
    phone: '+591',
    code: 'BO / BOL',
    flag: null,
  },
  {
    country: 'Bosnia and Herzegovina',
    phone: '+387',
    code: 'BA / BIH',
    flag: null,
  },
  {
    country: 'Botswana',
    phone: '+267',
    code: 'BW / BWA',
    flag: null,
  },
  {
    country: 'Brazil',
    phone: '+55',
    code: 'BR / BRA',
    flag: null,
  },
  {
    country: 'British Indian Ocean Territory',
    phone: '+246',
    code: 'IO / IOT',
    flag: null,
  },
  {
    country: 'British Virgin Islands',
    phone: '+1-284',
    code: 'VG / VGB',
    flag: null,
  },
  {
    country: 'Brunei',
    phone: '+673',
    code: 'BN / BRN',
    flag: null,
  },
  {
    country: 'Bulgaria',
    phone: '+359',
    code: 'BG / BGR',
    flag: null,
  },
  {
    country: 'Burkina Faso',
    phone: '+226',
    code: 'BF / BFA',
    flag: null,
  },
  {
    country: 'Burundi',
    phone: '+257',
    code: 'BI / BDI',
    flag: null,
  },
  {
    country: 'Cambodia',
    phone: '+855',
    code: 'KH / KHM',
    flag: null,
  },
  {
    country: 'Cameroon',
    phone: '+237',
    code: 'CM / CMR',
    flag: null,
  },
  {
    country: 'Canada',
    phone: '+1',
    code: 'CA / CAN',
    flag: flags.english,
  },
  {
    country: 'Cape Verde',
    phone: '+238',
    code: 'CV / CPV',
    flag: null,
  },
  {
    country: 'Cayman Islands',
    phone: '+1-345',
    code: 'KY / CYM',
    flag: null,
  },
  {
    country: 'Central African Republic',
    phone: '+236',
    code: 'CF / CAF',
    flag: null,
  },
  {
    country: 'Chad',
    phone: '+235',
    code: 'TD / TCD',
    flag: null,
  },
  {
    country: 'Chile',
    phone: '+56',
    code: 'CL / CHL',
    flag: null,
  },
  {
    country: 'China',
    phone: '+86',
    code: 'CN / CHN',
    flag: null,
  },
  {
    country: 'Christmas Island',
    phone: '+61',
    code: 'CX / CXR',
    flag: null,
  },
  {
    country: 'Cocos Islands',
    phone: '+61',
    code: 'CC / CCK',
    flag: null,
  },
  {
    country: 'Colombia',
    phone: '+57',
    code: 'CO / COL',
    flag: null,
  },
  {
    country: 'Comoros',
    phone: '+269',
    code: 'KM / COM',
    flag: null,
  },
  {
    country: 'Cook Islands',
    phone: '+682',
    code: 'CK / COK',
    flag: null,
  },
  {
    country: 'Costa Rica',
    phone: '+506',
    code: 'CR / CRI',
    flag: null,
  },
  {
    country: 'Croatia',
    phone: '+385',
    code: 'HR / HRV',
    flag: null,
  },
  {
    country: 'Cuba',
    phone: '+53',
    code: 'CU / CUB',
    flag: null,
  },
  {
    country: 'Curacao',
    phone: '+599',
    code: 'CW / CUW',
    flag: null,
  },
  {
    country: 'Cyprus',
    phone: '+357',
    code: 'CY / CYP',
    flag: null,
  },
  {
    country: 'Czech Republic',
    phone: '+420',
    code: 'CZ / CZE',
    flag: null,
  },
  {
    country: 'Democratic Republic of the Congo',
    phone: '+243',
    code: 'CD / COD',
    flag: null,
  },
  {
    country: 'Denmark',
    phone: '+45',
    code: 'DK / DNK',
    flag: null,
  },
  {
    country: 'Djibouti',
    phone: '+253',
    code: 'DJ / DJI',
    flag: null,
  },
  {
    country: 'Dominica',
    phone: '+1-767',
    code: 'DM / DMA',
    flag: null,
  },
  {
    country: 'Dominican Republic',
    phone: '+1-809, 1-829, 1-849',
    code: 'DO / DOM',
    flag: null,
  },
  {
    country: 'East Timor',
    phone: '+670',
    code: 'TL / TLS',
    flag: null,
  },
  {
    country: 'Ecuador',
    phone: '+593',
    code: 'EC / ECU',
    flag: null,
  },
  {
    country: 'Egypt',
    phone: '+20',
    code: 'EG / EGY',
    flag: null,
  },
  {
    country: 'El Salvador',
    phone: '+503',
    code: 'SV / SLV',
    flag: null,
  },
  {
    country: 'Equatorial Guinea',
    phone: '+240',
    code: 'GQ / GNQ',
    flag: null,
  },
  {
    country: 'Eritrea',
    phone: '+291',
    code: 'ER / ERI',
    flag: null,
  },
  {
    country: 'Estonia',
    phone: '+372',
    code: 'EE / EST',
    flag: null,
  },
  {
    country: 'Ethiopia',
    phone: '+251',
    code: 'ET / ETH',
    flag: null,
  },
  {
    country: 'Falkland Islands',
    phone: '+500',
    code: 'FK / FLK',
    flag: null,
  },
  {
    country: 'Faroe Islands',
    phone: '+298',
    code: 'FO / FRO',
    flag: null,
  },
  {
    country: 'Fiji',
    phone: '+679',
    code: 'FJ / FJI',
    flag: null,
  },
  {
    country: 'Finland',
    phone: '+358',
    code: 'FI / FIN',
    flag: null,
  },
  {
    country: 'France',
    phone: '+33',
    code: 'FR / FRA',
    flag: flags.french,
  },
  {
    country: 'French Polynesia',
    phone: '+689',
    code: 'PF / PYF',
    flag: null,
  },
  {
    country: 'Gabon',
    phone: '+241',
    code: 'GA / GAB',
    flag: null,
  },
  {
    country: 'Gambia',
    phone: '+220',
    code: 'GM / GMB',
    flag: null,
  },
  {
    country: 'Georgia',
    phone: '+995',
    code: 'GE / GEO',
    flag: null,
  },
  {
    country: 'Germany',
    phone: '+49',
    code: 'DE / DEU',
    flag: flags.deutsch,
  },
  {
    country: 'Ghana',
    phone: '+233',
    code: 'GH / GHA',
    flag: null,
  },
  {
    country: 'Gibraltar',
    phone: '+350',
    code: 'GI / GIB',
    flag: null,
  },
  {
    country: 'Greece',
    phone: '+30',
    code: 'GR / GRC',
    flag: null,
  },
  {
    country: 'Greenland',
    phone: '+299',
    code: 'GL / GRL',
    flag: null,
  },
  {
    country: 'Grenada',
    phone: '+1-473',
    code: 'GD / GRD',
    flag: null,
  },
  {
    country: 'Guam',
    phone: '+1-671',
    code: 'GU / GUM',
    flag: null,
  },
  {
    country: 'Guatemala',
    phone: '+502',
    code: 'GT / GTM',
    flag: null,
  },
  {
    country: 'Guernsey',
    phone: '+44-1481',
    code: 'GG / GGY',
    flag: null,
  },
  {
    country: 'Guinea',
    phone: '+224',
    code: 'GN / GIN',
    flag: null,
  },
  {
    country: 'Guinea-Bissau',
    phone: '+245',
    code: 'GW / GNB',
    flag: null,
  },
  {
    country: 'Guyana',
    phone: '+592',
    code: 'GY / GUY',
    flag: null,
  },
  {
    country: 'Haiti',
    phone: '+509',
    code: 'HT / HTI',
    flag: null,
  },
  {
    country: 'Honduras',
    phone: '+504',
    code: 'HN / HND',
    flag: null,
  },
  {
    country: 'Hong Kong',
    phone: '+852',
    code: 'HK / HKG',
    flag: null,
  },
  {
    country: 'Hungary',
    phone: '+36',
    code: 'HU / HUN',
    flag: null,
  },
  {
    country: 'Iceland',
    phone: '+354',
    code: 'IS / ISL',
    flag: null,
  },
  {
    country: 'India',
    phone: '+91',
    code: 'IN / IND',
    flag: flags.indian,
  },
  {
    country: 'Indonesia',
    phone: '+62',
    code: 'ID / IDN',
    flag: null,
  },
  {
    country: 'Iran',
    phone: '+98',
    code: 'IR / IRN',
    flag: null,
  },
  {
    country: 'Iraq',
    phone: '+964',
    code: 'IQ / IRQ',
    flag: null,
  },
  {
    country: 'Ireland',
    phone: '+353',
    code: 'IE / IRL',
    flag: null,
  },
  {
    country: 'Isle of Man',
    phone: '+44-1624',
    code: 'IM / IMN',
    flag: null,
  },
  {
    country: 'Israel',
    phone: '+972',
    code: 'IL / ISR',
    flag: null,
  },
  {
    country: 'Italy',
    phone: '+39',
    code: 'IT / ITA',
    flag: flags.italian,
  },
  {
    country: 'Ivory Coast',
    phone: '+225',
    code: 'CI / CIV',
    flag: null,
  },
  {
    country: 'Jamaica',
    phone: '+1-876',
    code: 'JM / JAM',
    flag: null,
  },
  {
    country: 'Japan',
    phone: '+81',
    code: 'JP / JPN',
    flag: null,
  },
  {
    country: 'Jersey',
    phone: '+44-1534',
    code: 'JE / JEY',
    flag: null,
  },
  {
    country: 'Jordan',
    phone: '+962',
    code: 'JO / JOR',
    flag: null,
  },
  {
    country: 'Kazakhstan',
    phone: '+7',
    code: 'KZ / KAZ',
    flag: null,
  },
  {
    country: 'Kenya',
    phone: '+254',
    code: 'KE / KEN',
    flag: null,
  },
  {
    country: 'Kiribati',
    phone: '+686',
    code: 'KI / KIR',
    flag: null,
  },
  {
    country: 'Kosovo',
    phone: '+383',
    code: 'XK / XKX',
    flag: null,
  },
  {
    country: 'Kuwait',
    phone: '+965',
    code: 'KW / KWT',
    flag: null,
  },
  {
    country: 'Kyrgyzstan',
    phone: '+996',
    code: 'KG / KGZ',
    flag: null,
  },
  {
    country: 'Laos',
    phone: '+856',
    code: 'LA / LAO',
    flag: null,
  },
  {
    country: 'Latvia',
    phone: '+371',
    code: 'LV / LVA',
    flag: null,
  },
  {
    country: 'Lebanon',
    phone: '+961',
    code: 'LB / LBN',
    flag: null,
  },
  {
    country: 'Lesotho',
    phone: '+266',
    code: 'LS / LSO',
    flag: null,
  },
  {
    country: 'Liberia',
    phone: '+231',
    code: 'LR / LBR',
    flag: null,
  },
  {
    country: 'Libya',
    phone: '+218',
    code: 'LY / LBY',
    flag: null,
  },
  {
    country: 'Liechtenstein',
    phone: '+423',
    code: 'LI / LIE',
    flag: null,
  },
  {
    country: 'Lithuania',
    phone: '+370',
    code: 'LT / LTU',
    flag: null,
  },
  {
    country: 'Luxembourg',
    phone: '+352',
    code: 'LU / LUX',
    flag: null,
  },
  {
    country: 'Macau',
    phone: '+853',
    code: 'MO / MAC',
    flag: null,
  },
  {
    country: 'Macedonia',
    phone: '+389',
    code: 'MK / MKD',
    flag: null,
  },
  {
    country: 'Madagascar',
    phone: '+261',
    code: 'MG / MDG',
    flag: null,
  },
  {
    country: 'Malawi',
    phone: '+265',
    code: 'MW / MWI',
    flag: null,
  },
  {
    country: 'Malaysia',
    phone: '+60',
    code: 'MY / MYS',
    flag: null,
  },
  {
    country: 'Maldives',
    phone: '+960',
    code: 'MV / MDV',
    flag: null,
  },
  {
    country: 'Mali',
    phone: '+223',
    code: 'ML / MLI',
    flag: null,
  },
  {
    country: 'Malta',
    phone: '+356',
    code: 'MT / MLT',
    flag: null,
  },
  {
    country: 'Marshall Islands',
    phone: '+692',
    code: 'MH / MHL',
    flag: null,
  },
  {
    country: 'Mauritania',
    phone: '+222',
    code: 'MR / MRT',
    flag: null,
  },
  {
    country: 'Mauritius',
    phone: '+230',
    code: 'MU / MUS',
    flag: null,
  },
  {
    country: 'Mayotte',
    phone: '+262',
    code: 'YT / MYT',
    flag: null,
  },
  {
    country: 'Mexico',
    phone: '+52',
    code: 'MX / MEX',
    flag: null,
  },
  {
    country: 'Micronesia',
    phone: '+691',
    code: 'FM / FSM',
    flag: null,
  },
  {
    country: 'Moldova',
    phone: '+373',
    code: 'MD / MDA',
    flag: null,
  },
  {
    country: 'Monaco',
    phone: '+377',
    code: 'MC / MCO',
    flag: null,
  },
  {
    country: 'Mongolia',
    phone: '+976',
    code: 'MN / MNG',
    flag: null,
  },
  {
    country: 'Montenegro',
    phone: '+382',
    code: 'ME / MNE',
    flag: null,
  },
  {
    country: 'Montserrat',
    phone: '+1-664',
    code: 'MS / MSR',
    flag: null,
  },
  {
    country: 'Morocco',
    phone: '+212',
    code: 'MA / MAR',
    flag: null,
  },
  {
    country: 'Mozambique',
    phone: '+258',
    code: 'MZ / MOZ',
    flag: null,
  },
  {
    country: 'Myanmar',
    phone: '+95',
    code: 'MM / MMR',
    flag: null,
  },
  {
    country: 'Namibia',
    phone: '+264',
    code: 'NA / NAM',
    flag: null,
  },
  {
    country: 'Nauru',
    phone: '+674',
    code: 'NR / NRU',
    flag: null,
  },
  {
    country: 'Nepal',
    phone: '+977',
    code: 'NP / NPL',
    flag: null,
  },
  {
    country: 'Netherlands',
    phone: '+31',
    code: 'NL / NLD',
    flag: null,
  },
  {
    country: 'Netherlands Antilles',
    phone: '+599',
    code: 'AN / ANT',
    flag: null,
  },
  {
    country: 'New Caledonia',
    phone: '+687',
    code: 'NC / NCL',
    flag: null,
  },
  {
    country: 'New Zealand',
    phone: '+64',
    code: 'NZ / NZL',
    flag: null,
  },
  {
    country: 'Nicaragua',
    phone: '+505',
    code: 'NI / NIC',
    flag: null,
  },
  {
    country: 'Niger',
    phone: '+227',
    code: 'NE / NER',
    flag: null,
  },
  {
    country: 'Nigeria',
    phone: '+234',
    code: 'NG / NGA',
    flag: null,
  },
  {
    country: 'Niue',
    phone: '+683',
    code: 'NU / NIU',
    flag: null,
  },
  {
    country: 'North Korea',
    phone: '+850',
    code: 'KP / PRK',
    flag: null,
  },
  {
    country: 'Northern Mariana Islands',
    phone: '+1-670',
    code: 'MP / MNP',
    flag: null,
  },
  {
    country: 'Norway',
    phone: '+47',
    code: 'NO / NOR',
    flag: null,
  },
  {
    country: 'Oman',
    phone: '+968',
    code: 'OM / OMN',
    flag: null,
  },
  {
    country: 'Pakistan',
    phone: '+92',
    code: 'PK / PAK',
    flag: null,
  },
  {
    country: 'Palau',
    phone: '+680',
    code: 'PW / PLW',
    flag: null,
  },
  {
    country: 'Palestine',
    phone: '+970',
    code: 'PS / PSE',
    flag: null,
  },
  {
    country: 'Panama',
    phone: '+507',
    code: 'PA / PAN',
    flag: null,
  },
  {
    country: 'Papua New Guinea',
    phone: '+675',
    code: 'PG / PNG',
    flag: null,
  },
  {
    country: 'Paraguay',
    phone: '+595',
    code: 'PY / PRY',
    flag: null,
  },
  {
    country: 'Peru',
    phone: '+51',
    code: 'PE / PER',
    flag: null,
  },
  {
    country: 'Philippines',
    phone: '+63',
    code: 'PH / PHL',
    flag: null,
  },
  {
    country: 'Pitcairn',
    phone: '+64',
    code: 'PN / PCN',
    flag: null,
  },
  {
    country: 'Poland',
    phone: '+48',
    code: 'PL / POL',
    flag: null,
  },
  {
    country: 'Portugal',
    phone: '+351',
    code: 'PT / PRT',
    flag: flags.portuguese,
  },
  {
    country: 'Puerto Rico',
    phone: '+1-787, 1-939',
    code: 'PR / PRI',
    flag: null,
  },
  {
    country: 'Qatar',
    phone: '+974',
    code: 'QA / QAT',
    flag: null,
  },
  {
    country: 'Republic of the Congo',
    phone: '+242',
    code: 'CG / COG',
    flag: null,
  },
  {
    country: 'Reunion',
    phone: '+262',
    code: 'RE / REU',
    flag: null,
  },
  {
    country: 'Romania',
    phone: '+40',
    code: 'RO / ROU',
    flag: null,
  },
  {
    country: 'Russia',
    phone: '+7',
    code: 'RU / RUS',
    flag: flags.russian,
  },
  {
    country: 'Rwanda',
    phone: '+250',
    code: 'RW / RWA',
    flag: null,
  },
  {
    country: 'Saint Barthelemy',
    phone: '+590',
    code: 'BL / BLM',
    flag: null,
  },
  {
    country: 'Saint Helena',
    phone: '+290',
    code: 'SH / SHN',
    flag: null,
  },
  {
    country: 'Saint Kitts and Nevis',
    phone: '+1-869',
    code: 'KN / KNA',
    flag: null,
  },
  {
    country: 'Saint Lucia',
    phone: '+1-758',
    code: 'LC / LCA',
    flag: null,
  },
  {
    country: 'Saint Martin',
    phone: '+590',
    code: 'MF / MAF',
    flag: null,
  },
  {
    country: 'Saint Pierre and Miquelon',
    phone: '+508',
    code: 'PM / SPM',
    flag: null,
  },
  {
    country: 'Saint Vincent and the Grenadines',
    phone: '+1-784',
    code: 'VC / VCT',
    flag: null,
  },
  {
    country: 'Samoa',
    phone: '+685',
    code: 'WS / WSM',
    flag: null,
  },
  {
    country: 'San Marino',
    phone: '+378',
    code: 'SM / SMR',
    flag: null,
  },
  {
    country: 'Sao Tome and Principe',
    phone: '+239',
    code: 'ST / STP',
    flag: null,
  },
  {
    country: 'Saudi Arabia',
    phone: '+966',
    code: 'SA / SAU',
    flag: null,
  },
  {
    country: 'Senegal',
    phone: '+221',
    code: 'SN / SEN',
    flag: null,
  },
  {
    country: 'Serbia',
    phone: '+381',
    code: 'RS / SRB',
    flag: null,
  },
  {
    country: 'Seychelles',
    phone: '+248',
    code: 'SC / SYC',
    flag: null,
  },
  {
    country: 'Sierra Leone',
    phone: '+232',
    code: 'SL / SLE',
    flag: null,
  },
  {
    country: 'Singapore',
    phone: '+65',
    code: 'SG / SGP',
    flag: null,
  },
  {
    country: 'Sint Maarten',
    phone: '+1-721',
    code: 'SX / SXM',
    flag: null,
  },
  {
    country: 'Slovakia',
    phone: '+421',
    code: 'SK / SVK',
    flag: null,
  },
  {
    country: 'Slovenia',
    phone: '+386',
    code: 'SI / SVN',
    flag: null,
  },
  {
    country: 'Solomon Islands',
    phone: '+677',
    code: 'SB / SLB',
    flag: null,
  },
  {
    country: 'Somalia',
    phone: '+252',
    code: 'SO / SOM',
    flag: null,
  },
  {
    country: 'South Africa',
    phone: '+27',
    code: 'ZA / ZAF',
    flag: null,
  },
  {
    country: 'South Korea',
    phone: '+82',
    code: 'KR / KOR',
    flag: null,
  },
  {
    country: 'South Sudan',
    phone: '+211',
    code: 'SS / SSD',
    flag: null,
  },
  {
    country: 'Spain',
    phone: '+34',
    code: 'ES / ESP',
    flag: flags.spanish,
  },
  {
    country: 'Sri Lanka',
    phone: '+94',
    code: 'LK / LKA',
    flag: null,
  },
  {
    country: 'Sudan',
    phone: '+249',
    code: 'SD / SDN',
    flag: null,
  },
  {
    country: 'Suriname',
    phone: '+597',
    code: 'SR / SUR',
    flag: null,
  },
  {
    country: 'Svalbard and Jan Mayen',
    phone: '+47',
    code: 'SJ / SJM',
    flag: null,
  },
  {
    country: 'Swaziland',
    phone: '+268',
    code: 'SZ / SWZ',
    flag: null,
  },
  {
    country: 'Sweden',
    phone: '+46',
    code: 'SE / SWE',
    flag: null,
  },
  {
    country: 'Switzerland',
    phone: '+41',
    code: 'CH / CHE',
    flag: null,
  },
  {
    country: 'Syria',
    phone: '+963',
    code: 'SY / SYR',
    flag: null,
  },
  {
    country: 'Taiwan',
    phone: '+886',
    code: 'TW / TWN',
    flag: null,
  },
  {
    country: 'Tajikistan',
    phone: '+992',
    code: 'TJ / TJK',
    flag: null,
  },
  {
    country: 'Tanzania',
    phone: '+255',
    code: 'TZ / TZA',
    flag: null,
  },
  {
    country: 'Thailand',
    phone: '+66',
    code: 'TH / THA',
    flag: null,
  },
  {
    country: 'Togo',
    phone: '+228',
    code: 'TG / TGO',
    flag: null,
  },
  {
    country: 'Tokelau',
    phone: '+690',
    code: 'TK / TKL',
    flag: null,
  },
  {
    country: 'Tonga',
    phone: '+676',
    code: 'TO / TON',
    flag: null,
  },
  {
    country: 'Trinidad and Tobago',
    phone: '+1-868',
    code: 'TT / TTO',
    flag: null,
  },
  {
    country: 'Tunisia',
    phone: '+216',
    code: 'TN / TUN',
    flag: null,
  },
  {
    country: 'Turkey',
    phone: '+90',
    code: 'TR / TUR',
    flag: null,
  },
  {
    country: 'Turkmenistan',
    phone: '+993',
    code: 'TM / TKM',
    flag: null,
  },
  {
    country: 'Turks and Caicos Islands',
    phone: '+1-649',
    code: 'TC / TCA',
    flag: null,
  },
  {
    country: 'Tuvalu',
    phone: '+688',
    code: 'TV / TUV',
    flag: null,
  },
  {
    country: 'U.S. Virgin Islands',
    phone: '+1-340',
    code: 'VI / VIR',
    flag: null,
  },
  {
    country: 'Uganda',
    phone: '+256',
    code: 'UG / UGA',
    flag: null,
  },
  {
    country: 'Ukraine',
    phone: '+380',
    code: 'UA / UKR',
    flag: null,
  },
  {
    country: 'United Arab Emirates',
    phone: '+971',
    code: 'AE / ARE',
    flag: null,
  },
  {
    country: 'United Kingdom',
    phone: '+44',
    code: 'GB / GBR',
    flag: null,
  },
  {
    country: 'United States',
    phone: '+1',
    code: 'US / USA',
    flag: null,
  },
  {
    country: 'Uruguay',
    phone: '+598',
    code: 'UY / URY',
    flag: null,
  },
  {
    country: 'Uzbekistan',
    phone: '+998',
    code: 'UZ / UZB',
    flag: null,
  },
  {
    country: 'Vanuatu',
    phone: '+678',
    code: 'VU / VUT',
    flag: null,
  },
  {
    country: 'Vatican',
    phone: '+379',
    code: 'VA / VAT',
    flag: null,
  },
  {
    country: 'Venezuela',
    phone: '+58',
    code: 'VE / VEN',
    flag: null,
  },
  {
    country: 'Vietnam',
    phone: '+84',
    code: 'VN / VNM',
    flag: null,
  },
  {
    country: 'Wallis and Futuna',
    phone: '+681',
    code: 'WF / WLF',
    flag: null,
  },
  {
    country: 'Western Sahara',
    phone: '+212',
    code: 'EH / ESH',
    flag: null,
  },
  {
    country: 'Yemen',
    phone: '+967',
    code: 'YE / YEM',
    flag: null,
  },
  {
    country: 'Zambia',
    phone: '+260',
    code: 'ZM / ZMB',
    flag: null,
  },
  {
    country: 'Zimbabwe',
    phone: '+263',
    code: 'ZW / ZWE',
    flag: null,
  },
  {
    country: 'Ukrainian',
    phone: '+38',
    code: 'UA',
    flag: null,
  },
]

export const getCountryFlagByPhoneNumber = (number = '') => {
  const result = PHONES.find(el => number.startsWith(el.phone))

  if (result) return result.flag
  return PHONES[0].flag
}

export const getCodeByNumber = (number = '') => {
  const result = PHONES.find(el => number.startsWith(el.phone))

  if (result) return result.code
  return PHONES[0].code
}

export default PHONES
